from .v1 import KEYWORD_GRAPH_PROMPT_V1
from .v2 import KEYWORD_GRAPH_PROMPT_V2
from .v3 import KEYWORD_GRAPH_PROMPT_V3
from .v3_eng import KEYWORD_GRAPH_PROMPT_V3_ENG
from .v4 import KEYWORD_GRAPH_PROMPT_V4
from .v5 import KEYWORD_GRAPH_PROMPT_V5
from .v6 import KEYWORD_GRAPH_PROMPT_V6
from .v7 import KEYWORD_GRAPH_PROMPT_V7
from .v8 import KEYWORD_GRAPH_PROMPT_V8
from .v9 import KEYWORD_GRAPH_PROMPT_V9


__all__ = ["KEYWORD_GRAPH_PROMPT_V1", "KEYWORD_GRAPH_PROMPT_V2", 
           "KEYWORD_GRAPH_PROMPT_V3", "KEYWORD_GRAPH_PROMPT_V3_ENG"
           "KEYWORD_GRAPH_PROMPT_V4", "KEYWORD_GRAPH_PROMPT_V5", 
           "KEYWORD_GRAPH_PROMPT_V6", "KEYWORD_GRAPH_PROMPT_V7",
           "KEYWORD_GRAPH_PROMPT_V8", "KEYWORD_GRAPH_PROMPT_V9"]
