from .v1 import KEYWORD_GRAPH_PROMPT_V1
from .v2 import KEYWORD_GRAPH_PROMPT_V2
from .v3 import KEYWORD_GRAPH_PROMPT_V3
from .v3_eng import KEYWORD_GRAPH_PROMPT_V3_ENG


__all__ = ["KEYWORD_GRAPH_PROMPT_V1", "KEYWORD_GRAPH_PROMPT_V2", "KEYWORD_GRAPH_PROMPT_V3", "KEYWORD_GRAPH_PROMPT_V3_ENG"]
